# Generated by Django 5.1.7 on 2025-05-08 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0002_remove_carrinho_itens_remove_carrinho_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='impressa_app.carrinho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='opcoes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='url_arquivo',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
