# Generated by Django 5.1.7 on 2025-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0003_pedido_carrinho_produto_opcoes_produto_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='tipo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
