# Generated by Django 5.1.7 on 2025-05-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0004_itemcarrinho_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
