# Generated by Django 5.1.7 on 2025-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0005_itemcarrinho_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
